### ISSUE TITLE
Customizations do not work on iOS. 

### ISSUE THREAD

**Issue by ediewoelfle** [messier16/PlatformTabbedPage#1]
I downloaded the NuGet for my Xamarin Forms app. The package is in both my iOS and Android projects, however, the customizations do not show on iOS. 

`SelectedColor = (Color)Application.Current.Resources["Info"];`

Above is my code to a color saved in my App.xaml. I can change that color to red, green, etc and have no change on iOS. 

`BarBackgroundColor = (Color)Application.Current.Resources["PrimaryLight"];`

The above code appears not to work on iOS, either. 

I am on Version 1.0.0.

**Comment by fferegrino** [comment]
Sorry for the late response. Is this still happening on version 2.0?
I'll close this issue for now, however, feel free to reopen it or create another if this is still happening.
