### ISSUE TITLE
No responses

### ISSUE THREAD

**Issue by clifzero** [messier16/PlatformTabbedPage#3]
Do you ever respond to your issues? Because quite frankly you don't although there aren't millions of people using your plugin I don't feel thats an excuse to not be of any assistance. I bet you'll ignore this as well.

**Comment by fferegrino** [comment]
As much as I want to keep these projects running for others to benefit, currently this is not my fulltime job (it has never been), and sometimes I do not have the time to go through the issues despite, as you mention, having just a few.

That being said I'm open to receiving PRs. But if that is not a possibility for you, try to reproduce your issue using the sample project located in [Sample](https://github.com/messier16/PlatformTabbedPage/tree/master/Sample) (use the SampleLocalApp.sln) or create a [mcve](https://stackoverflow.com/help/mcve) for me to work on, that would definitely help me and motivate me to try to solve any issues. 

Cheers!

**Comment by clifzero** [comment]
Thank you! You actually responded, the problem I'm currently facing with this plugin is the bar background colour of the iOS tab bar is too translucent, can't you add a property that allows us to choose whether or not we want the tab bar to be translucent or not, currently, a black tab bar background looks gray
